// ============================================================
// DUMMY DATA — SkyRoute
// ============================================================

export const AIRLINES = [
  { id: "1", name: "Biman Bangladesh Airlines", code: "BG", logo: "Plane", country: "Bangladesh" },
  { id: "2", name: "Emirates", code: "EK", logo: "Plane", country: "UAE" },
  { id: "3", name: "Qatar Airways", code: "QR", logo: "Plane", country: "Qatar" },
  { id: "4", name: "Singapore Airlines", code: "SQ", logo: "Plane", country: "Singapore" },
  { id: "5", name: "Turkish Airlines", code: "TK", logo: "Plane", country: "Turkey" },
  { id: "6", name: "Air Arabia", code: "G9", logo: "Plane", country: "UAE" },
];

export const AIRPORTS = [
  { id: "1", code: "DAC", name: "Hazrat Shahjalal International", city: "Dhaka", country: "Bangladesh" },
  { id: "2", code: "CGP", name: "Shah Amanat International", city: "Chittagong", country: "Bangladesh" },
  { id: "3", code: "DXB", name: "Dubai International", city: "Dubai", country: "UAE" },
  { id: "4", code: "DOH", name: "Hamad International", city: "Doha", country: "Qatar" },
  { id: "5", code: "SIN", name: "Changi Airport", city: "Singapore", country: "Singapore" },
  { id: "6", code: "LHR", name: "Heathrow Airport", city: "London", country: "UK" },
  { id: "7", code: "CDG", name: "Charles de Gaulle", city: "Paris", country: "France" },
  { id: "8", code: "KUL", name: "Kuala Lumpur International", city: "Kuala Lumpur", country: "Malaysia" },
  { id: "9", code: "BKK", name: "Suvarnabhumi Airport", city: "Bangkok", country: "Thailand" },
  { id: "10", code: "IST", name: "Istanbul Airport", city: "Istanbul", country: "Turkey" },
];

export const FLIGHTS = [
  {
    id: "F001",
    airline: "Biman Bangladesh Airlines",
    airlineCode: "BG",
    flightNumber: "BG-001",
    from: { code: "DAC", city: "Dhaka" },
    to: { code: "DXB", city: "Dubai" },
    departure: "06:00",
    arrival: "09:30",
    duration: "5h 30m",
    stops: 0,
    price: 32500,
    class: "Economy",
    baggage: "30kg",
    refundable: true,
    seats: 45,
  },
  {
    id: "F002",
    airline: "Emirates",
    airlineCode: "EK",
    flightNumber: "EK-582",
    from: { code: "DAC", city: "Dhaka" },
    to: { code: "DXB", city: "Dubai" },
    departure: "10:15",
    arrival: "13:45",
    duration: "5h 30m",
    stops: 0,
    price: 48000,
    class: "Economy",
    baggage: "35kg",
    refundable: true,
    seats: 20,
  },
  {
    id: "F003",
    airline: "Qatar Airways",
    airlineCode: "QR",
    flightNumber: "QR-642",
    from: { code: "DAC", city: "Dhaka" },
    to: { code: "DXB", city: "Dubai" },
    departure: "14:00",
    arrival: "19:15",
    duration: "7h 15m",
    stops: 1,
    stopCity: "Doha",
    price: 36000,
    class: "Economy",
    baggage: "30kg",
    refundable: false,
    seats: 8,
  },
  {
    id: "F004",
    airline: "Singapore Airlines",
    airlineCode: "SQ",
    flightNumber: "SQ-446",
    from: { code: "DAC", city: "Dhaka" },
    to: { code: "SIN", city: "Singapore" },
    departure: "23:55",
    arrival: "10:15",
    duration: "4h 20m",
    stops: 0,
    price: 42000,
    class: "Economy",
    baggage: "25kg",
    refundable: true,
    seats: 33,
  },
  {
    id: "F005",
    airline: "Turkish Airlines",
    airlineCode: "TK",
    flightNumber: "TK-714",
    from: { code: "DAC", city: "Dhaka" },
    to: { code: "IST", city: "Istanbul" },
    departure: "03:45",
    arrival: "13:20",
    duration: "11h 35m",
    stops: 0,
    price: 55000,
    class: "Economy",
    baggage: "30kg",
    refundable: true,
    seats: 15,
  },
];

export const DESTINATIONS = [
  {
    id: "1",
    name: "Cox's Bazar",
    country: "Bangladesh",
    description: "Home to the world's longest natural sea beach stretching 120km.",
    image: "https://images.unsplash.com/photo-1559827291-72ee739d0d9a?w=800&auto=format&fit=crop",
    tours: 24,
    rating: 4.8,
    type: "domestic",
  },
  {
    id: "2",
    name: "Maldives",
    country: "Maldives",
    description: "Crystal clear waters, pristine beaches, and luxurious overwater bungalows.",
    image: "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=800&auto=format&fit=crop",
    tours: 18,
    rating: 4.9,
    type: "international",
  },
  {
    id: "3",
    name: "Bangkok",
    country: "Thailand",
    description: "Vibrant city life, ancient temples, and world-renowned cuisine.",
    image: "https://images.unsplash.com/photo-1508009603885-50cf7c579365?w=800&auto=format&fit=crop",
    tours: 32,
    rating: 4.7,
    type: "international",
  },
  {
    id: "4",
    name: "Dubai",
    country: "UAE",
    description: "A futuristic city with towering skyscrapers and luxury shopping.",
    image: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800&auto=format&fit=crop",
    tours: 28,
    rating: 4.8,
    type: "international",
  },
  {
    id: "5",
    name: "Sundarbans",
    country: "Bangladesh",
    description: "The world's largest mangrove forest and home of the Royal Bengal Tiger.",
    image: "https://images.unsplash.com/photo-1559827291-72ee739d0d9a?w=800&auto=format&fit=crop",
    tours: 15,
    rating: 4.6,
    type: "domestic",
  },
  {
    id: "6",
    name: "Singapore",
    country: "Singapore",
    description: "A modern city-state where culture, nature and architecture coexist beautifully.",
    image: "https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=800&auto=format&fit=crop",
    tours: 22,
    rating: 4.8,
    type: "international",
  },
];

export const HOTELS = [
  {
    id: "H001",
    name: "Radisson Blu Dhaka Water Garden",
    location: "Dhaka, Bangladesh",
    stars: 5,
    rating: 4.7,
    reviews: 1240,
    pricePerNight: 8500,
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&auto=format&fit=crop",
    amenities: ["WiFi", "Pool", "Gym", "Spa", "Restaurant", "Bar"],
    type: "Luxury",
  },
  {
    id: "H002",
    name: "The Peninsula Bangkok",
    location: "Bangkok, Thailand",
    stars: 5,
    rating: 4.9,
    reviews: 2450,
    pricePerNight: 22000,
    image: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800&auto=format&fit=crop",
    amenities: ["WiFi", "Pool", "Gym", "Spa", "Restaurant", "Concierge"],
    type: "Luxury",
  },
  {
    id: "H003",
    name: "Atlantis The Palm Dubai",
    location: "Dubai, UAE",
    stars: 5,
    rating: 4.8,
    reviews: 5670,
    pricePerNight: 45000,
    image: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&auto=format&fit=crop",
    amenities: ["WiFi", "Waterpark", "Pool", "Gym", "Spa", "Multiple Restaurants"],
    type: "Resort",
  },
  {
    id: "H004",
    name: "Anantara Veli Maldives Resort",
    location: "Maldives",
    stars: 5,
    rating: 4.9,
    reviews: 3210,
    pricePerNight: 85000,
    image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&auto=format&fit=crop",
    amenities: ["WiFi", "Overwater Bungalow", "Pool", "Diving", "Spa", "Restaurant"],
    type: "Resort",
  },
  {
    id: "H005",
    name: "Pan Pacific Singapore",
    location: "Singapore",
    stars: 5,
    rating: 4.7,
    reviews: 1890,
    pricePerNight: 18000,
    image: "https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800&auto=format&fit=crop",
    amenities: ["WiFi", "Pool", "Gym", "Restaurant", "Bar", "Business Center"],
    type: "Business",
  },
  {
    id: "H006",
    name: "Long Beach Hotel Cox's Bazar",
    location: "Cox's Bazar, Bangladesh",
    stars: 4,
    rating: 4.4,
    reviews: 890,
    pricePerNight: 4500,
    image: "https://images.unsplash.com/photo-1531088009183-5ff5b7c95f91?w=800&auto=format&fit=crop",
    amenities: ["WiFi", "Pool", "Restaurant", "Beach Access", "Parking"],
    type: "Beach",
  },
];

export const TOUR_PACKAGES = [
  {
    id: "T001",
    title: "Maldives Bliss — 5 Days",
    destination: "Maldives",
    duration: "5 Days / 4 Nights",
    price: 125000,
    originalPrice: 145000,
    image: "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=800&auto=format&fit=crop",
    rating: 4.9,
    reviews: 342,
    type: "international",
    highlights: ["Overwater Villa", "Snorkeling", "Spa Package", "All Meals"],
    included: ["Flights", "Hotel", "Transfers", "Breakfast"],
    excluded: ["Visa", "Personal Expenses"],
    itinerary: [
      { day: 1, title: "Arrival & Check-in", description: "Arrive at Male Airport, speedboat transfer to resort." },
      { day: 2, title: "Underwater Exploration", description: "Snorkeling at house reef, sunset fishing." },
      { day: 3, title: "Island Hopping", description: "Visit local island, dolphin cruise." },
      { day: 4, title: "Relaxation & Spa", description: "Full body spa treatment, beach leisure." },
      { day: 5, title: "Departure", description: "Breakfast, checkout, and departure." },
    ],
    tag: "Best Seller",
  },
  {
    id: "T002",
    title: "Bangkok City & Beach Explorer — 7 Days",
    destination: "Thailand",
    duration: "7 Days / 6 Nights",
    price: 85000,
    originalPrice: 98000,
    image: "https://images.unsplash.com/photo-1508009603885-50cf7c579365?w=800&auto=format&fit=crop",
    rating: 4.7,
    reviews: 218,
    type: "international",
    highlights: ["Temple Tours", "Phuket Beach", "Thai Cooking Class", "Night Markets"],
    included: ["Flights", "Hotel (3★ & 4★)", "Breakfast", "City Tour"],
    excluded: ["Visa", "Lunch/Dinner", "Personal Expenses"],
    itinerary: [
      { day: 1, title: "Arrive Bangkok", description: "Airport transfer, hotel check-in." },
      { day: 2, title: "Grand Palace & Temples", description: "Guided tour of Wat Pho and Emerald Buddha." },
      { day: 3, title: "Floating Market", description: "Damnoen Saduak floating market visit." },
      { day: 4, title: "Fly to Phuket", description: "Internal flight, beach check-in at 4★ resort." },
      { day: 5, title: "Island Hopping Krabi", description: "Phi Phi Island tour by speedboat." },
      { day: 6, title: "Leisure Day", description: "Free day on Patong Beach." },
      { day: 7, title: "Departure", description: "Transfer to airport, fly home." },
    ],
    tag: "Most Popular",
  },
  {
    id: "T003",
    title: "Cox's Bazar Weekend Escape — 3 Days",
    destination: "Bangladesh",
    duration: "3 Days / 2 Nights",
    price: 12500,
    originalPrice: 15000,
    image: "https://images.unsplash.com/photo-1559827291-72ee739d0d9a?w=800&auto=format&fit=crop",
    rating: 4.5,
    reviews: 678,
    type: "domestic",
    highlights: ["Laboni Beach", "Himchori Waterfall", "Inani Beach", "Sunset Cruise"],
    included: ["Transport", "Hotel (3★)", "Breakfast", "Sightseeing"],
    excluded: ["Lunch/Dinner", "Personal Expenses"],
    itinerary: [
      { day: 1, title: "Dhaka to Cox's Bazar", description: "Morning bus/flight, hotel check-in, beach walk." },
      { day: 2, title: "Sightseeing", description: "Himchori, Inani Beach, evening on Laboni Beach." },
      { day: 3, title: "Departure", description: "Breakfast, checkout, journey back to Dhaka." },
    ],
    tag: "Budget Friendly",
  },
  {
    id: "T004",
    title: "Dubai Discovery — 6 Days",
    destination: "UAE",
    duration: "6 Days / 5 Nights",
    price: 165000,
    originalPrice: 185000,
    image: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800&auto=format&fit=crop",
    rating: 4.8,
    reviews: 455,
    type: "international",
    highlights: ["Burj Khalifa", "Desert Safari", "Dubai Mall", "Marina Cruise"],
    included: ["Flights", "Hotel (4★)", "Daily Breakfast", "City Tour", "Desert Safari"],
    excluded: ["Visa", "Personal Expenses"],
    itinerary: [
      { day: 1, title: "Arrive Dubai", description: "Airport pickup, hotel check-in, rest." },
      { day: 2, title: "City Tour", description: "Old Dubai, Gold Souk, Burj Al Arab view." },
      { day: 3, title: "Burj Khalifa & Mall", description: "At The Top experience, Dubai Mall visit." },
      { day: 4, title: "Desert Safari", description: "Dune bashing, camel ride, BBQ dinner." },
      { day: 5, title: "Marina & JBR", description: "Marina walk, Dhow cruise dinner." },
      { day: 6, title: "Departure", description: "Free morning, airport transfer." },
    ],
    tag: "Premium",
  },
];

export const VISA_COUNTRIES = [
  {
    id: "V001",
    country: "Malaysia",
    flag: "🇲🇾",
    processingTime: "3-5 Business Days",
    fee: 3500,
    type: "Tourist Visa",
    validity: "30 Days",
    requirements: ["Passport (6 months valid)", "Bank Statement", "Hotel Booking", "Passport Photo", "Itinerary"],
    image: "https://images.unsplash.com/photo-1596422846543-75c6fc197f07?w=400&auto=format&fit=crop",
  },
  {
    id: "V002",
    country: "Thailand",
    flag: "🇹🇭",
    processingTime: "5-7 Business Days",
    fee: 4200,
    type: "Tourist Visa",
    validity: "60 Days",
    requirements: ["Passport", "Bank Statement (3 months)", "Photos", "Return Ticket", "Travel Insurance"],
    image: "https://images.unsplash.com/photo-1508009603885-50cf7c579365?w=400&auto=format&fit=crop",
  },
  {
    id: "V003",
    country: "UAE (Dubai)",
    flag: "🇦🇪",
    processingTime: "2-3 Business Days",
    fee: 8500,
    type: "Tourist Visa",
    validity: "30 Days",
    requirements: ["Passport", "Colored Passport Photo", "Bank Statement", "Employment Letter"],
    image: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=400&auto=format&fit=crop",
  },
  {
    id: "V004",
    country: "Singapore",
    flag: "🇸🇬",
    processingTime: "7-10 Business Days",
    fee: 5000,
    type: "Tourist Visa",
    validity: "30 Days",
    requirements: ["Passport", "Photos", "Bank Statement", "Letter from Employer", "Hotel Booking"],
    image: "https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=400&auto=format&fit=crop",
  },
];

export const INSURANCE_PLANS = [
  {
    id: "I001",
    name: "Basic Traveler",
    price: 1500,
    duration: "7 Days",
    coverage: "USD 25,000",
    features: ["Medical Emergency", "Trip Cancellation", "Lost Baggage", "24/7 Support"],
    tag: null,
  },
  {
    id: "I002",
    name: "Standard Explorer",
    price: 3000,
    duration: "15 Days",
    coverage: "USD 50,000",
    features: ["Medical Emergency", "Trip Cancellation", "Lost Baggage", "Flight Delay", "Personal Accident", "24/7 Support"],
    tag: "Most Popular",
  },
  {
    id: "I003",
    name: "Premium Globe Trotter",
    price: 5500,
    duration: "30 Days",
    coverage: "USD 100,000",
    features: ["All Standard Features", "Adventure Sports", "Repatriation", "Pre-existing Conditions", "Emergency Dental", "Concierge Service"],
    tag: "Best Value",
  },
];

export const BLOGS = [
  {
    id: "B001",
    title: "Top 10 Budget Travel Destinations in Asia for 2025",
    excerpt: "Explore the most affordable yet breathtaking destinations Asia has to offer without breaking the bank.",
    author: "Sarah Ahmed",
    authorAvatar: "SA",
    date: "June 15, 2025",
    category: "Budget Travel",
    image: "https://images.unsplash.com/photo-1504598318550-17eba1008a68?w=800&auto=format&fit=crop",
    readTime: "5 min read",
  },
  {
    id: "B002",
    title: "A Complete Guide to Cox's Bazar: Everything You Need to Know",
    excerpt: "From the best beaches to local food spots — your ultimate guide to Bangladesh's number one tourist destination.",
    author: "Rahim Chowdhury",
    authorAvatar: "RC",
    date: "June 10, 2025",
    category: "Domestic Travel",
    image: "https://images.unsplash.com/photo-1559827291-72ee739d0d9a?w=800&auto=format&fit=crop",
    readTime: "8 min read",
  },
  {
    id: "B003",
    title: "Dubai: A First-Timer's Complete Travel Guide",
    excerpt: "Everything from visa requirements to the best local restaurants and hidden gems the city has to offer.",
    author: "Nadia Islam",
    authorAvatar: "NI",
    date: "May 28, 2025",
    category: "International Travel",
    image: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800&auto=format&fit=crop",
    readTime: "12 min read",
  },
  {
    id: "B004",
    title: "How to Pack Smart for a 2-Week Backpacking Trip",
    excerpt: "Expert tips and tricks from seasoned backpackers on what to bring and what to leave behind.",
    author: "James Miller",
    authorAvatar: "JM",
    date: "May 20, 2025",
    category: "Travel Tips",
    image: "https://images.unsplash.com/photo-1501555088652-021faa106b9b?w=800&auto=format&fit=crop",
    readTime: "6 min read",
  },
];

export const REVIEWS = [
  {
    id: "R001",
    name: "Tanzila Rahman",
    avatar: "TR",
    rating: 5,
    comment: "Absolutely seamless booking experience! The Cox's Bazar package was perfectly organized and the hotel was exactly as described. Will definitely book again.",
    destination: "Cox's Bazar Package",
    date: "June 2025",
  },
  {
    id: "R002",
    name: "Kamrul Hassan",
    avatar: "KH",
    rating: 5,
    comment: "Got my Dubai visa within 2 days! The customer support team was incredibly helpful throughout the process. Highly recommended for hassle-free travel.",
    destination: "Dubai Visa Service",
    date: "May 2025",
  },
  {
    id: "R003",
    name: "Farhana Akter",
    avatar: "FA",
    rating: 4,
    comment: "The Maldives package was a dream come true. Great value for the price. The overwater villa experience exceeded our expectations!",
    destination: "Maldives Package",
    date: "May 2025",
  },
  {
    id: "R004",
    name: "David Chen",
    avatar: "DC",
    rating: 5,
    comment: "Booked a flight from Dhaka to Singapore through this platform. Got the best price compared to other platforms. Super smooth experience!",
    destination: "Flight Booking",
    date: "April 2025",
  },
];

export const BOOKINGS = [
  {
    id: "BK001",
    type: "Flight",
    title: "Dhaka → Dubai",
    airline: "Biman Bangladesh Airlines",
    date: "Jul 15, 2025",
    returnDate: "Jul 22, 2025",
    status: "Confirmed",
    amount: 32500,
    passengers: 1,
    pnr: "BG7839XZ",
  },
  {
    id: "BK002",
    type: "Hotel",
    title: "Radisson Blu Dhaka Water Garden",
    checkIn: "Aug 1, 2025",
    checkOut: "Aug 4, 2025",
    rooms: 1,
    guests: 2,
    status: "Pending",
    amount: 25500,
    confirmationNo: "RBD7823",
  },
  {
    id: "BK003",
    type: "Tour",
    title: "Maldives Bliss — 5 Days",
    date: "Sep 10, 2025",
    status: "Confirmed",
    amount: 125000,
    travelers: 2,
    bookingRef: "MT-2025-001",
  },
  {
    id: "BK004",
    type: "Visa",
    title: "Malaysia Tourist Visa",
    submittedDate: "Jun 20, 2025",
    status: "Processing",
    amount: 3500,
    appNumber: "MV2025-4789",
  },
];

export const NOTIFICATIONS = [
  {
    id: "N001",
    title: "Booking Confirmed!",
    message: "Your flight BG-001 (DAC→DXB) has been confirmed. PNR: BG7839XZ",
    time: "2 hours ago",
    type: "success",
    read: false,
  },
  {
    id: "N002",
    title: "Special Offer Just for You",
    message: "Get 15% off on all Maldives packages this week. Limited slots available!",
    time: "1 day ago",
    type: "promo",
    read: false,
  },
  {
    id: "N003",
    title: "Visa Application Update",
    message: "Your Malaysia Tourist Visa application is under review. Expected delivery in 3-5 business days.",
    time: "2 days ago",
    type: "info",
    read: true,
  },
  {
    id: "N004",
    title: "Payment Received",
    message: "Payment of BDT 32,500 for BK001 has been received successfully.",
    time: "3 days ago",
    type: "success",
    read: true,
  },
];

export const DUMMY_USER = {
  id: "U001",
  name: "Ibrahim Khalil",
  email: "ibrahim@skyroute.com",
  phone: "+880 1700-000000",
  avatar: "IK",
  role: "user",
  joinDate: "January 2025",
  totalBookings: 4,
  totalSpent: 186500,
  passportNumber: "AB1234567",
  nationality: "Bangladeshi",
  dateOfBirth: "1990-01-15",
};

export const ADMIN_USER = {
  id: "A001",
  name: "Admin User",
  email: "admin@skyroute.com",
  avatar: "AD",
  role: "admin",
};

export const COUPONS = [
  { code: "TRAVEL20", discount: 20, type: "percent", minOrder: 10000, expiresAt: "Jul 31, 2025" },
  { code: "DHAKA500", discount: 500, type: "flat", minOrder: 5000, expiresAt: "Aug 15, 2025" },
  { code: "MALDIVES10", discount: 10, type: "percent", minOrder: 50000, expiresAt: "Sep 30, 2025" },
];

export const FAQS = [
  {
    question: "How do I book a flight?",
    answer: "Simply enter your origin, destination, and travel dates in the flight search box on our home page. Browse through available flights, select your preferred option, fill in passenger details, and complete payment.",
  },
  {
    question: "Can I cancel my booking?",
    answer: "Yes, you can cancel your booking from 'My Bookings' in your dashboard. Cancellation policies vary by airline and hotel. Please review the cancellation policy before booking.",
  },
  {
    question: "How long does visa processing take?",
    answer: "Visa processing times vary by country, typically from 2-10 business days. You can check the specific processing time on each visa country's detail page.",
  },
  {
    question: "What payment methods do you accept?",
    answer: "We accept all major credit/debit cards (Visa, Mastercard), mobile banking (bKash, Nagad, Rocket), and net banking.",
  },
  {
    question: "How do I get my e-ticket after booking a flight?",
    answer: "Your e-ticket will be sent to your registered email within 30 minutes of successful payment. You can also download it from 'My Bookings' in your dashboard.",
  },
  {
    question: "Do you offer group travel packages?",
    answer: "Yes! We offer customized group travel packages for 10+ travelers. Please contact our support team for group booking inquiries.",
  },
];

// Admin dashboard stats
export const ADMIN_STATS = {
  totalUsers: 24890,
  totalFlights: 1240,
  totalHotels: 860,
  totalPackages: 245,
  monthlyRevenue: 4850000,
  totalBookings: 8920,
};

export const MONTHLY_REVENUE_DATA = [
  { month: "Jan", revenue: 3200000, bookings: 620 },
  { month: "Feb", revenue: 2900000, bookings: 540 },
  { month: "Mar", revenue: 3800000, bookings: 720 },
  { month: "Apr", revenue: 4100000, bookings: 810 },
  { month: "May", revenue: 4500000, bookings: 890 },
  { month: "Jun", revenue: 4850000, bookings: 960 },
];

export const BOOKING_TYPE_DATA = [
  { name: "Flights", value: 45, color: "#3b82f6" },
  { name: "Hotels", value: 25, color: "#8b5cf6" },
  { name: "Tours", value: 20, color: "#f59e0b" },
  { name: "Visa", value: 10, color: "#10b981" },
];
